services:
  bars:
    container_name: parser
    build:
      context: .
    command:  bash -c "./wait-for-postgres.sh db ${POSTGRES_USER} ${POSTGRES_PASSWORD} ${POSTGRES_DB} python src/main.py"
    ports:
      - "${PORT}:8000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/{POSTGRES_DB}
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:latest
    container_name: flights_postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
  

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: flights_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - app_network

volumes:
  postgres_data:
  pgadmin_data:


networks:
  app_network:
    driver: bridge